export enum SupporterProfile {
  VEREADOR = 'VEREADOR',
  PREFEITO = 'PREFEITO',
  LIDER_COMUNITARIO = 'LÍDER COMUNITÁRIO',
  PRESIDENTE_ASSOCIACAO = 'PRESIDENTE ASSOCIAÇÃO',
  DEPUTADO = 'DEPUTADO', // Sugestão extra
  OUTRO = 'OUTRO',
}
